### ISSUE TITLE
Problem with minify

### ISSUE THREAD

**Issue by OskarBun** [jackfranklin/html-dist#16]
Love this package, the new update helps with specifying which tags to keep/remove :+1: 

But I can't seem to get it to run. 

Tried `html-dist --config html-dist.config-js --input index.html`, but couldn't find the command so tried `./node_modules/.bin/html-dist --config html-dist.config.js --input index.html` which worked until this error

> /Users/OskarBunyan/Documents/backtrackers/blogs/node_modules/html-dist/node_modules/html-minifier/dist/htmlminifier.js:536
>   if (global.console && global.console.log) {
>             ^
> 
> TypeError: Cannot read property 'console' of undefined

**Comment by HongJheLi** [comment]
Same problem existed in Windows, but passed in Ubuntu.
So sad...

**Comment by OskarBun** [comment]
I actually fixed this problem, but work has kept me from make a pull request.

on line 10 of bin/cli.js you want to change the regex to:

`var transpileRegex = new RegExp("(" + argv.config + ")");`

It was running the transpiler on the the node_modules and erroring, this should make it just run it on the config file

**Comment by HongJheLi** [comment]
@OskarBun  Thanks, but it's not working in my Windows 7 64bit.

**Comment by jackfranklin** [comment]
The whole way this thing is packaged such that you need config Babel to transpile the node_modules/html-dist folder is really messy and needs some thought. TBH I don't 100% remember why it was needed, but I hope to look into it soon. I'd love any PRs :+1:

**Comment by jackfranklin** [comment]
@OskarBun @HongJheLi as of 0.3.0, there is no longer any Babel parsing of the config file done, so you'll have to rewrite the imports, but I think this solves this issue. If it doesn't please comment and I will reopen.
