### ISSUE TITLE
fromHTML

### ISSUE THREAD

**Issue by OskarBun** [jackfranklin/html-dist#17]
Cannot access 'html-dist/html'. Perhaps include fromHTML in the index.js exports?

**Comment by jackfranklin** [comment]
This should work fine, because `lib/html` should exist. In `node_modules/html-dist/lib`, is there a file called `html.js` ?

**Comment by jackfranklin** [comment]
Ah got it; the docs are incorrect here. It's `html-dist/lib/html`. Apologies, I'll update the README.
