### ISSUE TITLE
Custom args not working

### ISSUE THREAD

**Issue by dara76** [jackfranklin/html-dist#23]
Running `html-dist --config my.config.js --input index.html --jsFile "bundle-v1.js"`

with the following 

Input  index.html

```
<html>
  <head>
  </head>
  <body>
  </body>
</html>
```

my.config.js

```
import {
  script,
  args
} from 'html-dist';

export default {
  outputFile: 'dist/index.html',
  minify: false,
  body: {
    appends: [
      script({
        src: args.jsFile
      })
    ]
  }
}
```

produces output

```
<html>

  <head></head>

  <body>
    <script></script>  
  </body>

</html>
```

The script tag is appended but no `src` is set.

Am I doing something wrong?

**Comment by jackfranklin** [comment]
No, that looks about right. You could `console.log(args)` and see if anything is being set? I suspect it's not making it through, although I'm not sure why.

**Comment by jackfranklin** [comment]
If you can reproduce this in a repo and put it on GitHub I can dive in and have a look :)

**Comment by jackfranklin** [comment]
The example in this repo (in the `example` folder) uses a custom argument and it's working just fine. Can you check v0.3.0 and see?

**Comment by dara76** [comment]
I'm using 0.2.2 alright. I'll take a look, and let you know.

**Comment by dara76** [comment]
Custom args work ok in v0.3.0.

**Comment by jackfranklin** [comment]
Great! No idea what changed but glad it's working.
