### ISSUE TITLE
Error running html-dist: fs.js:157 throw new ERR_INVALID_CALLBACK();

### ISSUE THREAD

**Issue by paulwellnerbou** [jackfranklin/html-dist#31]
Since I upgraded to node 10 I get this error running html-dist:

```
> html-dist --config html-dist.config.js --input www/index.html

Wrote to dist/index.html
fs.js:157
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:157:9)
    at Object.fs.writeFile (fs.js:1276:14)
    at /.../node_modules/html-dist/lib/run.js:94:18
    at /.../node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:183:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

This seems to be independent of the config, if I use the sample config documented here (https://www.npmjs.com/package/html-dist) I get the same error. I am using 0.3.2 now, but with 0.3.1 (which worked before with node 8) the same error happens. Am I doing something wrong?

**Comment by peteringram0** [comment]
The error looks like its coming from node. Ive upgraded to node 10.2.1 and able to run the example within the repo without any errors. Can you try running the example for me please 'yarn run cli-example' from inside the repo, see if you get any errors.

**Comment by peteringram0** [comment]
Closing due to no reply.
