### ISSUE TITLE
Is it right to remove ALL <script> tags?

### ISSUE THREAD

**Issue by fergusg** [jackfranklin/html-dist#4]
I'm thinking that external ones shouldn't be. Perhaps exclude URLs starting `http://` `https://` and `//` so if `href=` 

```
^(http(s)?:)?//)
```

I haven't tested that regex, but I'm sure you get the point.  

(Sorry, I'm not GITed up, so no pull request)

**Comment by fergusg** [comment]
Here's my best try

```
const re = RegExp('^((http(s)?:)?//)');

p.rm = function(e) {
  let src  = this.$(e).attr('src');
  if (src && !src.match(re)) {
    this.$(e).remove();
  }
}

p.removeAll = function() {
  this.$('script').each((i,e) => this.rm(e));
  return this;
}

```

**Comment by jackfranklin** [comment]
Yeah, some more clever options might be nicer.

I think the best approach here generally would be to make this module usable as an API. So you can use the CLI for basic uses, but then delve into a more expressive API once you have more specific requirements. What do you think to that?
